### PR TITLE
Spring Data JPA Content Assist

### LINKED ISSUE #107: add Spring Data JPA Content Assist to STS 4
Has Spring Data JPA Content Assist been removed from STS 4? In version 3 I was able to use content assist to show what fields were allowed to be part of the name of the method when using Query Methods. Has it been removed / not added to STS4 or is it a bug or disabled by default?

### PR DESCRIPTION
**Pull request by danthe1st**
Fixes #107

This PR adds more Content Assist options for Spring JPA Repository interfaces.

It adds simple text completions, e.g. a content assist is provided for `countBy` and automatically completes the return type and parameters of a method if it is named correctly.

https://user-images.githubusercontent.com/34687786/220149842-d878a24c-88be-4431-81f8-138247b120e0.mp4

Aside from that, it includes a small fix allowing for primitive properties and also boolean properties if their getter names start with `is`.

To do:
- ~~Order/priorize completion proposals if possible (put text proposals at the bottom of the proposal list) - I am unsure whether this is possible~~ does not seem to be possible without significant modifications and Eclipse seems to order it in a sensitive way anyways
- [x] more tests :)
- [x] split up some methods for better readability
- [x] Add completion proposals for property names (e.g. `findByFirst` should could completed to `findByFirstName`)
- [x] improve content assist for complex types that are indirectly referenced `findByEmployee_FirstName` so that it detects the type
- [x] complete partial attribute names (e.g. complete `findByFirst` to `findByFirstName`)

Future work:
- The keywords `In`/`IsIn` should make the method expect a collection whereas `Includes`/... should expect a single element when a collection is on the left
- create text-completions for keywords

Should there be a method/configuration for enabling/disabling these content assist options (e.g. enable some but not others)? If so, where/how are such things implemented in this project?

### CODE REVIEW

**Comment by BoykoAlex** [comment]
@danthe1st Generally it all looks good to me. I suspect that the way to use it would be first type in the query keyword with a help of content assist (query proposals) then invoke content assist once query string is completed to fill in the rest for the method declaration (method proposals). Is this correct?
I'm going to squash the commits into one before merging. Hope this is okay with you

**Comment by danthe1st** [comment]
Yes, it does complete the signature of already existing queries once they are typed (if those refer to unknown attributes, it uses `Object` as the parameter).

Aside from that, it also autocompletes simple query method subjects like `findFirst`.

I decided to return `List`s (except for `streamBy`) in the query methods.

As seen in the `Future work` section, there still potential to improve it but I decided that those things could be done in upcoming PRs.

Finally, squashing is perfectly fine with me.

**Comment by BoykoAlex** [comment]
I'm going to merge this PR as is squashed and rebased. It looks like we could factor some static stuff into spring beans but we can do it later as more PRs in this area are merged

**Comment by BoykoAlex** [comment]
Squashed, rebased and merged with 97d66062c0c40fb6caf3d4c06862daee3ae2a066

**Pull request closed without merging**
