### PR TITLE
refine walkthrough steps

### PR DESCRIPTION
**Pull request by Eskibear**
As discussed, we will have 4 steps for users to follow:
- create a new project/open a sample project 
- explore projects, e.g. view symbols 
- run projects
- view live information

I'll update SVG files with new commits once they are ready.

### CODE REVIEW

**Comment by Eskibear** [comment]
Changes in cf7043e :
- Step 1: add a button to git.clone(vscode's command) petclinic into a location you choose. vscode handles the UX.
- Step 2: remove the instruction about adding "@" in the workspace symbols inputbox as we now pre-input "#@" when you click the command.
- Step 3: add a button to run the project
- Step 4: add buttons to open beans and mappings views. Memory view is not showing all the time, we can show the memory graph in the image, telling users that we have this fancy feature.

**Comment by martinlippert** [comment]
The changes look good to me, just missing the SVG files.

**Comment by Tanyatang0** [comment]
Here are the SVG files.
Step1_commandPalette
Step1_commandPalette
Step2_Explore your project
Step2_Explore your project
Step3_Run your project
Step3_Run your project
Step4_View live information from your running application
Step4_View live information from your running application
Attached is the image zip file. @Eskibear
[Steps image file.zip](https://github.com/microsoft/vscode-java-internal/files/10139504/Steps.image.file.zip)

**Comment by Eskibear** [comment]
@Tanyatang0 Thank you for creating the SVGs, they look good. Below are some nits in other themes, is it possible to address them? Below screenshots are captured in `Kimbie Dark` theme.

Step 1:
image

Step 2:
image

Step 3:
Color of bean/mapping icons should be the same with project icons above (the circle). 
image

**Comment by Eskibear** [comment]
@martinlippert I just updated the themed SVGs. Please take a look.

**Pull request merged**
