### PR TITLE
vscode-concourse: add dark background to light mode icon

### PR DESCRIPTION
**Pull request by bmalehorn**
Add a new icon with a dark foreground, to be displayed on light color themes.

Follow-up to https://github.com/spring-projects/sts4/pull/839.

| before | after |
| --- | --- |
| image | image |

### CODE REVIEW

**Comment by martinlippert** [comment]
Hey @bmalehorn, thanks a lot for jumping on this. I meant a dark FOREGROUND and a transparent background, much in the same way than the dark-mode-icon has a white foreground and a transparent background. What do you think?

**Comment by martinlippert** [comment]
(and sorry for the confusion)

**Comment by bmalehorn** [comment]
> Hey @bmalehorn, thanks a lot for jumping on this. I meant a dark FOREGROUND and a transparent background, much in the same way than the dark-mode-icon has a white foreground and a transparent background. What do you think?

Ah no worries. I've updated the PR to have a dark icon on transparent background. But come to think of it, I kind of prefer the white-on-blue icon, which is the only official icon colors that you'll see on https://concourse-ci.org/. I like icons to have a bit of color so they're easier to pick out from each other. So maybe things can be left as-is?

light mode: white on blue, like https://concourse-ci.org/
dark mode: white on transparent, like a hosted concourse instance

I don't have a super strong preference either way and just like having any icons at all.

**Comment by martinlippert** [comment]
finally picked the new icon-black for the light mode here, looks nicely consistent now between light and dark theme. Thanks again @bmalehorn for contributing this!!!

**Pull request merged**
