### PR TITLE
Fix #173 : Add support for filtering project symbols

### LINKED ISSUE #173: [navigation] Allow filtering by project in Find Spring Elements list
The default implementation is to show spring elements in workspace or on current file. It would be really usefull if the elements can be filtered on the current project as well. One could easily filter the elements by their path using the current active editor's project name. This can be programmed to another cycle of CTRL+6 like workspace, project and current file.  Or else one could program it to be able filter using a different keyword in the filter field. I personally prefer the option 1 since it make the user experience more straight forward.

### PR DESCRIPTION
**Pull request by gayanper**
Add new provider which will filter symbols for the current selected
resource's project in GoTo Symbol dialog.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@gayanper Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/sts?repositoryId=spring-projects/sts4&pullRequestId=174)!

[Click here](https://cla.pivotal.io/sync/sts?repositoryId=spring-projects/sts4&pullRequestId=174) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@gayanper Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/sts?repositoryId=spring-projects/sts4&pullRequestId=174)!

**Comment by gayanper** [comment]
any feedback on this ? :)

**Comment by martinlippert** [comment]
Looks good to me. The only missing piece is the copyright header in the new `InProjectSymbolsProvider`, please add and update the PR.

**Comment by gayanper** [comment]
@martinlippert update the copyright header :+1:

**Comment by martinlippert** [comment]
great, maybe one more small fix? The Copyright header mentions 2017, should be 2019... :-)

**Comment by martinlippert** [comment]
Never mind, merged the PR and will do the fix for the copyright year myself. Many many thanks for the contribution, very much appreciated !!!

**Pull request merged**
