### PR TITLE
Track symbol dependencies ...

### PR DESCRIPTION
**Pull request by kdvolder**
@martinlippert I got something working that handles 'symbol' dependencies. 

I would welcome feedback before merging to master.

I sill need to figure out how to add tests for the dependency tracking. I.e. to test scenario where one file depends on another, other file is changed and then the symbols from the first file should update.

(Note: already added tests for the 'on disk cache' support. But that isnt really enough since it doesn't actually test the logic of the dependency data is discovered and used, only how it gets stored). 

I'll continue working on this tomorrow. Priority one will be to add a few tests for the depenency discovery and use. There's also a couple more optimisations that re left as //TODO in the code, which I might think about (though for now I think my priority is first on making sure it works correctly without these optimisations).

Synopsis of how this works:

1) while scanning a file, we keep track of when data is read from a ITYpeBiding. So for example, when we read a constant from a type 'Foo' then a 'dependency' on type 'Foo' is recorded for the current file.

2) during scanning of a file we keep track also of 'scanned types'.

3) at the end of a single-file scan, we check whether the 'scanned types' are dependencies of other scanned files. If yes, then all these files are considered 'affected' and we trigger a scan for them as well.

4) Step 3 is repeated until no additional files get scanned (this is guaranteed to terminate because we keep track of which files have already been scanned and so we never scan the same file twice.

### CODE REVIEW

**Comment by martinlippert** [comment]
One question: why do you track the types that are affected instead of the documents? That way you would not need to record which types are declared in which documents, but instead just trigger re-scanning of those documents. Would make the code simpler, I think. WDYT?

**Comment by kdvolder** [comment]
I thought about tracking the documents, the main reason I didn't do it is because it's not totally obvious how you would get from an 'ITypeBinding' reference to find the document it came from. This could be complex because:

- Different cases depending on what kind of type it is (anonymous type nested type, etc)
- there's not an easy 'textual' rule that you can use to take the fq name of a typebinding and find the corresponding file (you'd have to search for it on the classpath because it could have come from any package fragment root).

So I'm not sure this would make things simpler. It would make certain aspects simpler. Yes, analyzing dependecy between files is simpler than analyzing dependency between file -> type, but I think actually discovering the dependencies would be more complex and possibly bug-prone (more cases to consider?).

This all assumes that it is indeed a bit tricky (and possibly slow) to go from a 'ITypeBinding' and finding the document/file it came from. Maybe I am wrong and I missed some easy API in JDT that can do this. If you know of such API please tell me, I will also take another look today and think about this again.

**Comment by martinlippert** [comment]
I totally agree that trying to find the document ourselves starting from the type (and looking at the classpath) doesn't make a lot of sense. I thought that you might be able to find that from the binding or the type, but if that isn't the case, then it looks like we have to track the things in the way you implemented it. Usually you can get the file via the IJavaElement, asking that for the resource, but since we don't feed the parser with that IResource objects, it doesn't return anything for the IJavaElement.

**Comment by martinlippert** [comment]
I am fine with merging this for the 4.3.0 release.

**Comment by kdvolder** [comment]
Okay, in that case I will merge it now. I'll file a follow up ticket about some potential optimisations, including considering switching to file-based dependency tracking instead of type-based (I didn't do this yet because I instead spent time setting up some regression tests... I figured that would be more important as it helps in making sure things work correctly, and then its 'safer' to work on optimisation afterwards.

**Pull request merged**
